Update npm_release.yml

diff --git a/.github/workflows/npm_release.yml b/.github/workflows/npm_release.yml
--- a/.github/workflows/npm_release.yml
+++ b/.github/workflows/npm_release.yml
@@ -38,6 +38,13 @@ jobs:
           openapi-generator-cli version-manager set 7.12.0
       - run: npm i
       - run: npm run start
-      - run: npm publish --access restricted
+      - name: Retry npm publish on conflict
+        run: |
+          for i in {1..5}; do
+            npm publish --access restricted && break || {
+              echo "❗ Publish failed, retrying in 10s... ($i/5)"
+              sleep 10
+            }
+          done
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PRIVATE }}
